name: Merge Commit Message Update
on:
  pull_request:
    types:
      - synchronize
      - ready_for_review

jobs:
  update-merge-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full history

      - name: Fetch all branches
        run: |
          git fetch origin +refs/heads/${{ github.event.pull_request.head.ref }}:refs/remotes/origin/${{ github.event.pull_request.head.ref }}
          git fetch origin +refs/heads/${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}

      - name: Get all commits from PR
        run: |
          git log --pretty=format:"%s" origin/${{ github.event.pull_request.base.ref }}..origin/${{ github.event.pull_request.head.ref }} > commit_messages.txt

      - name: Display commit messages
        run: cat commit_messages.txt
